name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build tests
        run: cargo test --no-run

      - name: Find test executable
        run: echo "TEST_EXECUTABLE=$(find ./target/debug/deps/ -type f -executable -name 'as_root-*')" >> $GITHUB_ENV

      - name: Run root-required test user_and_group_does_not_exist
        run: sudo -E $TEST_EXECUTABLE --show-output --ignored --test user_and_group_does_not_exist
        env:
          TEST_EXECUTABLE: ${{ env.TEST_EXECUTABLE }}

      - name: Run root-required test change_to_nobody_and_nogroup
        run: sudo -E $TEST_EXECUTABLE --show-output --ignored --test change_to_nobody_and_nogroup
        env:
          TEST_EXECUTABLE: ${{ env.TEST_EXECUTABLE }}

      - name: Run tests
        run: cargo test -- --show-output
