name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build tests
        run: cargo test --no-run
      - name: Find test executable
        run: |
          if [[ "$(uname)" == "Darwin" ]]; then
            echo "TEST_EXECUTABLE=$(find ./target/debug/deps -type f -perm +111 -name 'as_root-*')" >> $GITHUB_ENV
          else
            echo "TEST_EXECUTABLE=$(find ./target/debug/deps -type f -executable -name 'as_root-*')" >> $GITHUB_ENV
          fi
      - name: Run root-required test user_and_group_does_not_exist
        run: sudo -E -- $TEST_EXECUTABLE --show-output --ignored --test user_and_group_does_not_exist
        env:
          TEST_EXECUTABLE: ${{ env.TEST_EXECUTABLE }}
      - name: Run root-required test change_to_nobody_and_nogroup
        run: sudo -E -- $TEST_EXECUTABLE --show-output --ignored --test change_to_nobody_and_nogroup
        env:
          TEST_EXECUTABLE: ${{ env.TEST_EXECUTABLE }}
      - name: Run tests
        run: cargo test -- --show-output
      - name: Check without logging feature
        run: cargo check --no-default-features
      - name: Run tests without logging feature
        run: cargo test --no-default-features -- --show-output

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings